//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SequentialScript.Test.CustomData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SequentialScript.Test.CustomData.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OPEN]
        ///run
        /// Block -&gt; Some Action /NoCheck /Key1:Value /Key2:&quot;Value with spaces&quot; /Key3:&quot;Value with special characters :/&quot;
        ///as @action.
        /// </summary>
        internal static string TestArguments {
            get {
                return ResourceManager.GetString("TestArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OPEN]
        ///
        ///// Comment over block
        ///run // Comment in block
        /// 
        /// // Comment over instruction
        /// Door -&gt; Open // Comment in instruction
        ///
        ///as @open_door // Comment at the end of the block.
        /// </summary>
        internal static string TestComments {
            get {
                return ResourceManager.GetString("TestComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OPEN]
        ///run
        /// Block -&gt; Some Action /NoCheck /Key1:Value /Key2:&quot;Value with spaces&quot; /Key3:&quot;Value with special characters :/&quot;
        /// Delay 3000
        ///as @action.
        /// </summary>
        internal static string TestDelay {
            get {
                return ResourceManager.GetString("TestDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OPEN]
        ///run
        /// Door Light -&gt; Enable
        ///as @open_door_1
        ///
        ///when @open_door_1
        ///run
        /// Door -&gt; Open
        ///as @open_door_2
        ///
        ///when @open_door_1, @open_door_2
        ///run
        /// Door Light -&gt; Disable
        ///as @open_door_3.
        /// </summary>
        internal static string TestDependences {
            get {
                return ResourceManager.GetString("TestDependences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OPEN]
        ///run
        /// Door Light -&gt; Enable
        ///as @open_door_1
        ///
        ///when @open_door_1, @open_door_3
        ///run
        /// Door -&gt; Open
        ///as @open_door_2
        ///
        ///when @open_door_1, @open_door_2
        ///run
        /// Door Light -&gt; Disable
        ///as @open_door_3.
        /// </summary>
        internal static string TestDependences_Recursivity {
            get {
                return ResourceManager.GetString("TestDependences_Recursivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [HYDROGEN_STOCKPILE]
        ///run
        /// Hydrogen Example (Thruster) -&gt; Disable
        ///as @thrusters_disabled
        ///
        ///run
        /// Hydrogen Example (Status LCD) -&gt; Set /Index:-1 /Background:YELLOW /Text:Connecting...
        /// Hydrogen Example (Piston) -&gt; Extend
        ///as @piston_extended
        ///
        ///when @piston_extended
        ///run
        /// Hydrogen Example (Connector) -&gt; Connect
        ///as @connector_locked
        ///
        ///when @connector_locked
        ///run
        /// Hydrogen Example (Status LCD) -&gt; Set /Index:-1 /Background:BLUE /Text:Recharging...
        /// Hydrogen Example (Tank) -&gt; Stockpile
        ///as @tank_full
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestHydrogen {
            get {
                return ResourceManager.GetString("TestHydrogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OPEN]
        ///run
        /// Door -&gt; Open
        ///as @open_door.
        /// </summary>
        internal static string TestSimple {
            get {
                return ResourceManager.GetString("TestSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TEST]
        ///run
        /// Block 1 -&gt; Enabled
        /// Block 2 -&gt; Enabled
        ///as @block_name
        ///
        ///run
        /// Block 3 -&gt; Enabled
        /// Block 4 -&gt; Enabled
        /// Block 5 -&gt; Enabled
        ///as @block_name
        ///.
        /// </summary>
        internal static string TestSyntaxAliasDuplicated {
            get {
                return ResourceManager.GetString("TestSyntaxAliasDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TEST]
        ///run
        /// Air Vent -&gt; Depressurize
        ///as @room_depressurized
        ///
        ///when @room_depressurized
        ///run
        /// Door 1 -&gt; Enable
        /// Door 1 -&gt; Open
        ///as door_opened.
        /// </summary>
        internal static string TestSyntaxAliasInvalid {
            get {
                return ResourceManager.GetString("TestSyntaxAliasInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TestSyntaxInstructionInvalid {
            get {
                return ResourceManager.GetString("TestSyntaxInstructionInvalid", resourceCulture);
            }
        }
    }
}
